# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActsAccess',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('issuerid', models.IntegerField(blank=True, null=True)),
                ('revokeid', models.IntegerField(blank=True, null=True)),
                ('rid', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('creationdate', models.DateField()),
                ('revokedate', models.DateField(blank=True, null=True)),
                ('contact', models.BooleanField()),
            ],
            options={
                'db_table': 'acts_access',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApiAccessTokens',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('client_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'acts_api_access_tokens',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApiApps',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('organisation_id', models.IntegerField(blank=True, null=True)),
                ('random_id', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField()),
                ('secret', models.CharField(max_length=255)),
                ('allowed_grant_types', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('app_type', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField()),
                ('website', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'acts_api_apps',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApiAuthCodes',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('client_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('redirect_uri', models.TextField()),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'acts_api_auth_codes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApiAuthorisations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('externalapp_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'acts_api_authorisations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApiRefreshTokens',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('client_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'acts_api_refresh_tokens',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsApplications',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('showid', models.IntegerField(blank=True, null=True)),
                ('socid', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('deadlinedate', models.DateField()),
                ('furtherinfo', models.TextField()),
                ('deadlinetime', models.TimeField()),
            ],
            options={
                'db_table': 'acts_applications',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsAuditions',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('showid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('display', models.BooleanField()),
                ('nonscheduled', models.BooleanField()),
            ],
            options={
                'db_table': 'acts_auditions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsEvents',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('socid', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('endtime', models.TimeField()),
                ('starttime', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('linkid', models.IntegerField()),
            ],
            options={
                'db_table': 'acts_events',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsExternalUsers',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(max_length=50)),
                ('remote_id', models.CharField(max_length=100, blank=True)),
                ('username', models.CharField(max_length=255, blank=True)),
                ('name', models.CharField(max_length=255, blank=True)),
                ('token', models.CharField(max_length=255, blank=True)),
                ('email', models.CharField(max_length=255, blank=True)),
                ('profile_picture_url', models.CharField(max_length=255, blank=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acts_external_users',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsKnowledgebase',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('pageid', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'acts_knowledgebase',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsNameAliases',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'acts_name_aliases',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsPendingaccess',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('issuerid', models.IntegerField()),
                ('rid', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('creationdate', models.DateField()),
            ],
            options={
                'db_table': 'acts_pendingaccess',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsPeopleData',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=128, blank=True, unique=True)),
                ('mapto', models.IntegerField()),
                ('norobots', models.BooleanField()),
            ],
            options={
                'db_table': 'acts_people_data',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsPerformances',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('venid', models.IntegerField(blank=True, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('excludedate', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'acts_performances',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsShows',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('socid', models.IntegerField(blank=True, null=True)),
                ('venid', models.IntegerField(blank=True, null=True)),
                ('authorizeid', models.IntegerField(blank=True, null=True)),
                ('primaryref', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('facebook_id', models.CharField(max_length=50, blank=True)),
                ('twitter_id', models.CharField(max_length=50, blank=True)),
                ('slug', models.CharField(max_length=128, blank=True, unique=True)),
                ('dates', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True)),
                ('prices', models.CharField(max_length=255, blank=True)),
                ('photourl', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=255, blank=True)),
                ('excludedate', models.DateField(blank=True, null=True)),
                ('society', models.CharField(max_length=255, blank=True)),
                ('techsend', models.BooleanField()),
                ('actorsend', models.BooleanField()),
                ('audextra', models.TextField(blank=True)),
                ('entered', models.BooleanField()),
                ('entryexpiry', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('bookingcode', models.CharField(max_length=255, blank=True)),
                ('timestamp', models.DateTimeField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('freebase_id', models.CharField(max_length=255, blank=True)),
                ('facebookurl', models.CharField(max_length=2083, blank=True)),
                ('otherurl', models.CharField(max_length=2083, blank=True)),
                ('onlinebookingurl', models.CharField(max_length=2083, blank=True)),
            ],
            options={
                'db_table': 'acts_shows',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsShowsPeopleLink',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'acts_shows_people_link',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsSimilarNames',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('equivalence', models.BooleanField()),
            ],
            options={
                'db_table': 'acts_similar_names',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsSocieties',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('facebook_id', models.CharField(max_length=50, blank=True)),
                ('twitter_id', models.CharField(max_length=50, blank=True)),
                ('shortname', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100, blank=True)),
                ('affiliate', models.BooleanField()),
                ('logourl', models.CharField(max_length=255, blank=True)),
                ('slug', models.CharField(max_length=128, blank=True, unique=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.TextField(blank=True)),
                ('longitude', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'acts_societies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsTechies',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('showid', models.IntegerField(blank=True, null=True)),
                ('positions', models.TextField()),
                ('contact', models.TextField()),
                ('deadline', models.BooleanField()),
                ('deadlinetime', models.TimeField()),
                ('expiry', models.DateField()),
                ('display', models.BooleanField()),
                ('remindersent', models.BooleanField()),
                ('techextra', models.TextField()),
                ('lastupdated', models.DateTimeField()),
            ],
            options={
                'db_table': 'acts_techies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActsUsers',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pass_field', models.CharField(max_length=32, blank=True, db_column='pass')),
                ('registered', models.DateField()),
                ('login', models.DateField()),
                ('contact', models.BooleanField()),
                ('alumni', models.BooleanField()),
                ('publishemail', models.BooleanField()),
                ('hearabout', models.TextField()),
                ('occupation', models.CharField(max_length=255, blank=True)),
                ('graduation', models.CharField(max_length=255, blank=True)),
                ('tel', models.CharField(max_length=50, blank=True)),
                ('dbemail', models.NullBooleanField()),
                ('dbphone', models.NullBooleanField()),
                ('forumnotify', models.NullBooleanField()),
                ('threadmessages', models.NullBooleanField()),
                ('reversetime', models.BooleanField()),
                ('resetcode', models.CharField(max_length=32, blank=True)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField()),
                ('profile_picture_url', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'acts_users',
            },
            bases=(models.Model,),
        ),
    ]
