# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0003_auto_20150114_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='default_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='from_addr',
            field=models.EmailField(max_length=254, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='pendinggroupmember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='termdate',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)]),
        ),
    ]
